### ISSUE TITLE
pre class="example" does not escape HTML code

### ISSUE THREAD

**Issue by laurentperez** [speced/respec#305]
If I want to provide a HTML example, the following does not work, the div gets interpreted

```
<pre class="example highlight">
<div class="xxx">foo</div>
</pre>
```

If I use CDATA nothing is rendered at all.

Do I have to escape it on my own ? 

Thanks

**Comment by pumba-lt** [comment]
I know this is an old thread, but why is `CDATA` not supported?

**Comment by marcoscaceres** [comment]
No idea, tbh... isn't that some old school xml thing?

**Comment by halindrome** [comment]
Hysterical @marcoscaceres .  @pumba-lt it isn't supported because CDATA sections are deprecated.  

Here's a technique that I have used many times.


1) Provide a mechanism to transform your example (javascript updateExample method).
2) Put your example in a pre block
3) comment out the entire example

The updateExample method extracts the contents of the comment and injects it with proper escaping.

`        function updateExample(doc, content) {
          // perform transformations to make it render and prettier
          content = content.replace(//, '');
          content = _esc(content);
          content = content.replace(/\*\*\*\*([^*]*)\*\*\*\*/g, '<span class="hilite">$1</span>') ;
          return content ;
        }

        function _esc(s) {
            s = s.replace(/&/g,'&amp;');
            s = s.replace(/>/g,'&gt;');
            s = s.replace(/"/g,'&quot;');
            s = s.replace(/</g,'&lt;');
            return s;
        }
`


`<pre class='example' data-transform='updateExample' title="Example of an XHTML+RDFa 1.1 document"></pre>
`

**Comment by marcoscaceres** [comment]
> Hysterical @marcoscaceres
That was an honest question for once. 

Fixed the code above for you @halindrome. If you want multiline code, you need three back ticks.
